### ISSUE TITLE
Issue under 700px and text

### ISSUE THREAD

**Issue by fore0045** [fore0045/Picture-This#1]
Good evening professor Abhay, 

I have been trying to troubleshoot the following issues that I am facing with my assignment for hours and this is the last chance that I found to understand why I am getting the following errors: 

- Under 700px the .title class is not taking the 100% width. ( I tried several ways to fix it but I did not find why it is showing that white space on the right). At some point the space switches to the image. 
- When .title is being shown in columns, the text is not being centered vertically. I used vertical-align: middle and baseline, I even tried having a flex inside. 

I hope you can help me to understand the reason and I am sorry for bothering you. 

Thanks, Luisa

@abhaysharma

**Comment by fore0045** [comment]
Hello professor Abhay, 

I closed the issue. I tried to fix it again but I could not. 

Kind regards,

**Comment by abhaysharma** [comment]
@fore0045 I see that you have fixed the alignment of the text. The only thing remaining regarding your issue is the width of the image. You will need to add: 
```
img{ 
    width: 100%; 
}
```

Few other items to fix:

1. Add `box-sizing: border-box;` to the html.
2. Remove `flex: 1;` from .hreader, flex is used for the flex items to give them a flex-grow value of 1, it will not have any effect in the container.
3. Remove `align-items and `vertical-align` from `.title`, these properties are not used
4. Remove `image{ flex:1; }` image is not valid tag name, also your image is not a direct child of the header which is the flex container
5. Add `picture, .title{ flex: 1;}` in the media query so that both the flex items get equal growth.

**Comment by fore0045** [comment]
Hello Professor Abhay, 

Thank you very much for your help, I guess I got mad at this and I started even typing wrongly. I have also to practice Flex as I prefer Grid but I tried to use it for this assignment and I don't know why it didn't work for me. 

Kind regards,

**Comment by abhaysharma** [comment]
@fore0045 I hope the solutions above were helpful and you were able to solve the issue.
